# Generated by Django 2.2 on 2019-04-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190423_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_list',
            new_name='task_list_id',
        ),
    ]
